version: "3.2"

x-common-variables: &common-variables
  CELERY_BROKER_URL: amqp://guest@rabbitmq:5672

services:

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672

  app: &app
    build: .
    environment:
      <<: *common-variables
    depends_on:
      - rabbitmq

  flower:
    <<: *app
#    command: bash -c "celery -A evoker.workers flower --broker_api=amqp://guest@rabbitmq:15672/api"
    command: bash -c "celery -A evoker.workers flower"
    ports:
      - 5555:5555
    depends_on:
      - rabbitmq

  worker:
    <<: *app
    command: bash -c "celery -A evoker.workers worker"
    depends_on:
      - rabbitmq
