#!/usr/bin/env python3

import sys
import argparse
from datetime import datetime
from time import sleep

from evoker.io import writeln
from evoker.workers import make_request


def run(args):
    i = 0
    while True:
        i += 1
        writeln(f"[{datetime.now().isoformat()}] Iteration started #{i}")

        for url in args.urls:
            make_request.delay(
                url=url,
                concurrency=args.concurrency,
                detailed=args.debug
            )

        sleep(args.interval)


def main():
    parser = argparse.ArgumentParser(description='$END$')
    parser.add_argument('urls', metavar='N', type=str, nargs='+',
                        help='urls to be called')
    parser.add_argument('-d', '--debug', dest='debug', action='store_true',
                        help='set debug log level')
    parser.add_argument('-c', '--concurrency', dest='concurrency', type=int,
                        default=10, help='number of concurrent requests')
    parser.add_argument('-i', '--interval', dest='interval', type=float,
                        default=5, help='repeat every X seconds')
    args = parser.parse_args()

    writeln('Evoking started!\n')
    writeln('Press Ctrl+C to exit')
    writeln('')

    try:
        run(args=args)
    except KeyboardInterrupt:
        pass

    return 0


if __name__ == '__main__':
    sys.exit(main())
